.editorconfig, .github/workflows/build.yml, .github/workflows/lint.yml, README.md, jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/InterruptionDialog.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/property/ClockPropertyFactory.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordPropertyAdapter.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ActivitiesTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AutomaticInterruptionTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/DayTableTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTestBase.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ManualInterruptionTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/TableCellEditTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/JavaFxTable.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/TestUtil.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/TimeUtil.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/AutomaticInterruptionDialog.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/InterruptionDialog.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/JavaFxTable.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/model/DayActivities.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/model/DayRecord.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/scheduling/PeriodicTrigger.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/scheduling/ReschedulingRunnable.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/model/DayActivitiesTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/model/DayRecordTest.java
=> Minor improvements

README.md, jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/DurationStringConverter.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivitiesTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/converter/DurationStringConverter.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/tray/SwingUtil.java, jfxui/src/test/java/org/itsallcode/whiterabbit/jfxui/table/DurationStringConverterTest.java, jfxui/src/test/java/org/itsallcode/whiterabbit/jfxui/table/converter/DurationStringConverterTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/DayTableTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTestBase.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/TimeUtil.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/AutomaticInterruptionDialog.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/Config.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/ConfigFile.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppService.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/ClientConnection.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/RegistrationResult.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/RegistrationResultImpl.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/SingleInstanceServer.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/SingleInstanceService.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/SingleInstanceServiceDummyImpl.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/singleinstance/SingleInstanceServiceImpl.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/singleinstance/RegistrationResultImplTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/singleinstance/SingleInstanceServiceImplTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/singleinstance/SingleInstanceServiceTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/test/TestingConfig.java
=> More improvements

README.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AutomaticInterruptionTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/DayTableTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppServiceCallback.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/DelegatingAppServiceCallback.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/Interruption.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/WorkingTimeService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/AppServiceTest.java, textui/src/main/java/org/itsallcode/whiterabbit/textui/App.java
=> #15 freeze end time

.github/workflows/build.yml, README.md, build.gradle, jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/MenuBarBuilder.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AboutDialogUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/AboutDialogWindow.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, logic/build.gradle, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppPropertiesService.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/AppPropertiesServiceTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/AppServiceTest.java
=> Prepare release

README.md, build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ConfigCommandLineArgUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTestBase.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/Config.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/ConfigLoader.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/ConfigLoaderTest.java, textui/src/main/java/org/itsallcode/whiterabbit/textui/App.java, textui/src/test/java/org/itsallcode/whiterabbit/textui/AppTest.java
=> Custom config location

README.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/feature/InterruptionPresetFeature.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AddInterruptionTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AutomaticInterruptionTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/AddInterruptionDialog.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppService.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/WorkingTimeService.java
=> Add interruption presets

jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/property/ClockPropertyFactory.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivityPropertyAdapter.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordTable.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ActivitiesTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/DayTableTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/TableCellEditTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/TimeUtil.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/JavaFxTable.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/DayReporter.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/scheduling/PeriodicTrigger.java
=> Select current day

README.md, build.gradle, jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AboutDialogUiTest.java, logic/build.gradle, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppPropertiesService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/AppPropertiesServiceTest.java
This increases the JAR size from 12 to 13 MB but supports all three platforms.
=> Build a single-platform jar

.github/workflows/build.yml, README.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/PropertyField.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/DayTableTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/TableCellEditTest.java
=> #40: Keep edit focus when table is updated every minute

README.md, jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivitiesTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivityPropertyAdapter.java, jfxui/src/main/resources/log4j2.xml, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ActivitiesTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/TableCellEditTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/TimeUtil.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ActivitiesTable.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/JavaFxTable.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/model/DayActivities.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/project/Project.java, logic/src/test/resources/log4j2-test.xml, textui/src/main/resources/log4j2.xml, webstart/content/whiterabbit.jnlp
=> #42 Focus loss activities table

jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/UiActions.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/service/DesktopService.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/service/FakeDesktopService.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/service/RealDesktopService.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/MenuBarBuilder.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/StopWorkingTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/VacationReportTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/AutomaticInterruptionDialog.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/Config.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/ConfigFile.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/project/ProjectService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/ConfigFileTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/test/TestingConfig.java
=> #21: Add menu items for opening config files

CHANGELOG.md, README.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/AppState.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivitiesTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ActivitiesTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java
=> #44 update activities duration

CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/widget/AutoCompleteTextField.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/widget/PersistOnFocusLossTextFieldTableCell.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AutocompleteTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/TableCellEditTest.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteEntrySupplier.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteProposal.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteService.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/TextIndex.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteServiceTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/autocomplete/TextIndexTest.java
=> #52: Focus popup, add UI-Test

.gitignore, CHANGELOG.md, README.md, jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/App.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/log/LoggingConfigurator.java, jfxui/src/main/resources/log4j2.xml, logic/src/main/java/org/itsallcode/whiterabbit/logic/Config.java
=> #59 configure log path

jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/widgets/TableStateManager.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/uistate/widgets/TreeTableStateManager.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/plugin/PluginWrapper.java
=> Fix UI state when column count changes

.gitignore, jfxui/build.gradle, logic/src/main/java/org/itsallcode/whiterabbit/logic/report/project/ProjectReportImpl.java, plugins/pmsmart/build.gradle, plugins/pmsmart/src/main/java/org/itsallcode/whiterabbit/plugin/pmsmart/PMSmartExporter.java, plugins/pmsmart/src/main/java/org/itsallcode/whiterabbit/plugin/pmsmart/web/Element.java, plugins/pmsmart/src/main/java/org/itsallcode/whiterabbit/plugin/pmsmart/web/page/ProjectRow.java, plugins/pmsmart/src/main/java/org/itsallcode/whiterabbit/plugin/pmsmart/web/page/WeekViewPage.java, plugins/pmsmart/src/test/java/org/itsallcode/whiterabbit/plugin/pmsmart/web/page/ProjectRowTest.java
=> #74 export commments to pmsmart

CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordPropertyAdapter.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java, jfxui/src/main/resources/org/itsallcode/whiterabbit/jfxui/table/style.css, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/JavaFxTable.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/model/MonthIndex.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/model/MonthIndexTest.java
=> Highlight weekends and non-working days

jfxui/build.gradle, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordPropertyAdapter.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordTable.java
=> Fix highlighting of weekend and non-working days.

.github/workflows/build.yml, CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/converter/CustomLocalTimeStringConverter.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/days/DayRecordTable.java, jfxui/src/test/java/org/itsallcode/whiterabbit/jfxui/table/converter/CustomLocalTimeStringConverterTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/DayTableTest.java
=> #108 simplify time entry

CHANGELOG.md, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/autocomplete/TextIndexTest.java
=> #127: Fix order of most frequently used texts in autocomplete

CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivitiesTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/ActivitiesTest.java
=> #131: Allow deleting activities via Delete key

api/src/main/java/org/itsallcode/whiterabbit/api/AbstractPlugin.java, plugins/csv/src/main/java/org/itsallcode/whiterabbit/plugin/csv/CSVExporterPlugin.java, plugins/holiday-calculator/src/main/java/org/itsallcode/whiterabbit/plugin/holidaycalculator/HolidayCalculatorPlugin.java
moved from CSVExporterPlugin and HolidayCalculatorPlugin
to AbstractPlugin
fixes #115
=> 115 resolved duplicated code

.github/workflows/build-infrastructure.yml, .github/workflows/build.yml, .vscode/settings.json, .vscode/tasks.json, webstart-infrastructure/package-lock.json, webstart-infrastructure/package.json
Test with Java 16
Cleanup
Upgrade dependencies
=> test-java16

CHANGELOG.md, README.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/JavaFxApp.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/ApplicationHelper.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/MonthIndexStorage.java
Closes #177.
Save month if holidays where added.
=> #177: Add buttons for selecting the previous/next month

CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/table/activities/ActivitiesTable.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/model/DayRecord.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/model/DayRecordTest.java
=> #148: Bugfix: add activity to empty day

.github/workflows/build-infrastructure.yml, CHANGELOG.md, build.gradle, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/WorkingTimeService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/AppServiceTest.java
=> #210-skip2min-interruptions

CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/service/DesktopService.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/service/RealDesktopService.java, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/tray/SwingUtil.java
See https://bugs.openjdk.java.net/browse/JDK-8096706?focusedCommentId=13785982&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13785982
=> Fix opening files on Ubuntu

CHANGELOG.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/ui/AppUi.java
=> #147: Don't close main window when Escape key is typed

.github/workflows/build.yml, CHANGELOG.md, api/src/main/java/org/itsallcode/whiterabbit/api/features/Holidays.java, api/src/main/java/org/itsallcode/whiterabbit/api/features/MonthDataStorage.java, api/src/main/java/org/itsallcode/whiterabbit/api/features/ProgressMonitor.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/ActivityData.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/DayData.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/DayType.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/MonthData.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/Project.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/ProjectReport.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/ProjectReportActivity.java, api/src/main/java/org/itsallcode/whiterabbit/api/model/ProjectReportDay.java, build.gradle, jfxui/src/main/resources/log4j2.xml, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTest.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteEntrySupplier.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteService.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/CachingStorage.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/CachingStorageImpl.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/MonthCache.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/storage/Storage.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/autocomplete/AutocompleteServiceTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/storage/CachingStorageImplTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/storage/MonthCacheTest.java, settings.gradle
=> #250 Fix autocomplete cache

CHANGELOG.md, docs/developer_guide.md, jfxui/src/main/java/org/itsallcode/whiterabbit/jfxui/UiActions.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/AboutDialogUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/JavaFxAppUiTest.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/AboutDialogWindow.java, jfxui/src/uiTest/java/org/itsallcode/whiterabbit/jfxui/testutil/model/DayTable.java, logic/build.gradle, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/AppPropertiesService.java
=> #254: Show Java version in About dialog

CHANGELOG.md, jfxui/src/test/java/org/itsallcode/whiterabbit/jfxui/table/converter/DurationStringConverterTest.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/FormatterService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/service/FormatterServiceTest.java
=> #132: Fix formatting of negative zero duration

CHANGELOG.md, docs/user_guide.md, logic/src/main/java/org/itsallcode/whiterabbit/logic/Config.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/ConfigFile.java, logic/src/main/java/org/itsallcode/whiterabbit/logic/service/contract/ContractTermsService.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/ConfigFileTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/ConfigTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/model/DayRecordTest.java, logic/src/test/java/org/itsallcode/whiterabbit/logic/test/TestingConfig.java
=> #276: Consider interruption in mandatory break
